apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: rabbitmq-blue
    version: blue
  name: rabbitmq-blue
  namespace: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-blue
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rabbitmq-blue
        version: blue
    spec:
      containers:
      - env:
        - name: NODENAME
          value: rabbitmq-sl-1@localhost
        - name: RABBITMQ_MNESIA_DIR
          value: $RABBITMQ_MNESIA_BASE/rabbitmq-suitelog
        image: rabbitmq
        name: rabbitmq-blue
        ports:
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: 5672
          name: rabbitmq
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
        - mountPath: /etc/rabbitmq/
          name: config-volume
      volumes:
      - name: rabbitmq-blue
        persistentVolumeClaim:
          claimName: rabbitmq-blue
      - configMap:
          defaultMode: 420
          items:
          - key: enabled_plugins
            path: enabled_plugins
          - key: rabbitmq.conf
            path: rabbitmq.conf
          name: rabbitmq-config
        name: config-volume
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: rabbitmq-green
    version: green
  name: rabbitmq-green
  namespace: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-green
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rabbitmq-green
        version: green
    spec:
      containers:
      - env:
        - name: NODENAME
          value: rabbitmq-sl-1@localhost
        - name: RABBITMQ_MNESIA_DIR
          value: $RABBITMQ_MNESIA_BASE/rabbitmq-suitelog
        image: rabbitmq
        name: rabbitmq-green
        ports:
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: 5672
          name: rabbitmq
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
        - mountPath: /etc/rabbitmq/
          name: config-volume
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq-green
      - configMap:
          defaultMode: 420
          items:
          - key: enabled_plugins
            path: enabled_plugins
          - key: rabbitmq.conf
            path: rabbitmq.conf
          name: rabbitmq-config
        name: config-volume